export { WireError } from './errors.js'
export { Writer, VARINT_MAX, VARINT_MIN } from './writer.js'
export { Reader } from './reader.js'
export {
  type Codec,
  type Decoded,
  u8,
  u16,
  u32,
  varuint,
  varint,
  bool,
  str,
  bytes,
  fixedBytes,
  array,
  optional,
  enumOf,
  struct,
  encode,
  decode,
  sizeOf,
} from './codec.js'
export {
  FrameKind,
  MAX_PLAYERS,
  MAX_INPUT_REDUNDANCY,
  INPUT_REDUNDANCY_DEFAULT,
  INPUT_REDUNDANCY_BLE,
  BLE_SAFE_PAYLOAD_BYTES,
  BLE_LINK_BYTES_PER_SEC,
  type InputFrame,
  type TickBatchFrame,
  inputFrameCodec,
  tickBatchCodec,
  frame,
  frameKind,
  frameFlags,
  KIND_MASK,
  FLAG_MASK,
  FLAG_FRAGMENT,
  frameBody,
} from './protocol.js'
